services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3010:3010"
    environment:
      - ORDER_SERVICE_URL=http://order-service:3001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3002
    depends_on:
      - order-service
      - restaurant-service

  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
      - PORT=3001     
      - DELIVERY_SERVICE_URL=http://delivery-service:3003

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
      - PORT=3002

  delivery-service:
    build: ./delivery-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
      - PORT=3003
      - ORS_API_KEY = "5b3ce3597851110001cf6248e516113c76694476b8b2cfbd0efb7661"
      - ORDER_SERVICE_URL=http://order-service:3001

  payment-service:
    build: ./payment-service
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
      - PORT=3004

  user-service:
    build: ./user-service
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
      - PORT=3005
      - JWT_SECRET=f72d352a9cf052e3b4d18e4a0dddc0babc19e5cdc31f7c14991edba212b05d38
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - NODE_ENV=development