apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  MONGO_URI: mongodb+srv://Kasun:Kasun@cluster0.rj9xr.mongodb.net/FoodDB?retryWrites=true&w=majority
  PORT: "3001"
  DELIVERY_SERVICE_URL: http://delivery-service:3003
